language: ruby
cache: bundler
rvm: 3.2.3

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document

script: script/cibuild

env:
  matrix:
    - JEKYLL_VERSION="~> 3.8"
    - JEKYLL_VERSION="~> 4.0"
